#!/bin/sh

sxhkd &

bspc monitor -d 'ONE ' 'TWO ' 'THREE ' 'FOUR ' 'FIVE ' 'SIX ' 'SEVEN ' 'EIGHT ' 'NINE ' 'TEN ' 

xrdb -merge ${HOME}.Xresources
background=$(xrdb -query | grep "background" | cut -f2 | head -n 1)
foreground=$(xrdb -query | grep "foreground" | cut -f2 | head -n 1)
color0=$(xrdb -query | grep "color0" | cut -f2 | head -n 1)
color1=$(xrdb -query | grep "color1" | cut -f2 | head -n 1)
color2=$(xrdb -query | grep "color2" | cut -f2 | head -n 1)
color3=$(xrdb -query | grep "color3" | cut -f2 | head -n 1)
color4=$(xrdb -query | grep "color4" | cut -f2 | head -n 1)
color5=$(xrdb -query | grep "color5" | cut -f2 | head -n 1)
color6=$(xrdb -query | grep "color6" | cut -f2 | head -n 1)
color7=$(xrdb -query | grep "color7" | cut -f2 | head -n 1)
color8=$(xrdb -query | grep "color8" | cut -f2 | head -n 1)
color9=$(xrdb -query | grep "color9" | cut -f2 | head -n 1)


bspc config border_width         3
bspc config window_gap           8
bspc config right_padding        5
bspc config left_padding         5
bspc config top_padding          35
bspc config bottom_padding       35
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config normal_border_color $color3
bspc config active_border_color $color1
bspc config focused_border_color $color1
bspc config presel_feedback_color $color1

sxhkd &
${HOME}/.config/polybar/launch.sh
feh --bg-scale ~/.tmp/wp
picom --experimental-backends --blur-method dual_kawase --blur-strength 5
