#! /bin/sh

sxhkd &

bspc monitor -d HOME NET CHAT MUSIC V VI VII VIII IX X
bspc monitor DP2 -d HOME NET CHAT MUSIC V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           7
bspc config top_padding          35
bspc config bottom_padding       0
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a spotify desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color2"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
# Use the line below if you are on bspwm < 0.9.4
#bspc config presel_border_color "$color1"i

wal -R -o ~/.config/dunst/wal.sh
compton
$HOME/.config/polybar/launch.sh

